### ISSUE TITLE
Merge with `sup-heliotrope/ncursesw-ruby`

### ISSUE THREAD

**Issue by avtobiff** [rlane/ncursesw-ruby#3]
Hi!

It seems that some significant changes has been made to ncursesw-ruby elsewhere.

Can they me merged? See sup-heliotrope/ncursesw-ruby#14 for reference.
## 

Per

**Comment by gauteh** [comment]
Greetings,

we at sup-heliotrope would be happy to continue maintaining the `ncursesw` gem. Gem ownership should then be given to the current maintainers of sup-heliotrope and possibly also a dedicated ncursesw responsible. The current maintainers are known on github as: @foobacca, @rakoo and me, @gauteh.

If you agree, there are two options: Either remove: `$ gem yank` the gem (possibly all versions) and the namespace will be freed. Or delegate ownership, `$ gem owner email` to us as well (I prefer the latter).

In any of the cases, we will rename the gem at https://github.com/sup-heliotrope/ncursesw-ruby to: `ncursesw` and publish it. We will then eventually remove our current `ncursesw-sup` gem from rubygems.

Cheers, Gaute

**Comment by rlane** [comment]
I added @gauteh and @rakoo as owners to ncursesw. @foobacca didn't have an email listed on GitHub but I assume one of the new owners can add him.

**Comment by gauteh** [comment]
Thank you, we will.
