### ISSUE TITLE
example programs do not work with ruby1.9

### ISSUE THREAD

**Issue by yabuki** [rlane/ncursesw-ruby#4]
read_line.rb and tclock.rb do not work with ruby1.9

you need to write code like below

  when RUBY_VERSION.to_f <= 1.8 ? " "[0]..255  : (" "[0].ord)..255 # remaining printables

**Comment by gauteh** [comment]
There is a corresponding issue in: https://github.com/sup-heliotrope/ncursesw-ruby/issues/19#issuecomment-33340038 which is more actively maintained.

**Comment by yabuki** [comment]
I switched @gauteh repository.
